### ISSUE TITLE
Stop copying test files to `es` and `lib`

### ISSUE THREAD

**Issue by becca-bailey** [FormidableLabs/victory#2320]
As a part of #2301, we moved our tests to the directories they are testing. This required a few config updates in order to get everything compiling correctly.

However, we ran into a conflict between tests and typescript. In order to package our generated type files with Victory, we are using the `--copy-files` flag in our babel CLI commands. This takes all files that have not been transformed with babel and copies them to the `es` and `lib` packaged output directories. 

We have some ability to configure which files are copied by ignoring certain files in the babel build process and using the `--no-copy-ignored` flag. However, `.d.ts` files are also ignored by babel, so this doesn't work for our use case.

As a temporary measure, we are copying all files, including test files to the compiled output, and we have set up both jest and npm to ignore these copied test files. 

Eventually, we should make sure these test files are not copied at all. This might involve some more advanced babel configuration, using another build tool, or removing our dependency on babel altogether once the typescript conversion is complete.

**Comment by ryan-roemer** [comment]
My changes in https://github.com/FormidableLabs/victory/pull/2305/files took care of all this I think -- although I thought those were merged already?

@scottrippey do you know what happened?

**Comment by ryan-roemer** [comment]
I think this was fixed after `move-tests` was merged to main.

For a clean build in a JS-based project and TS-based project:

```sh
$ lerna exec --scope victory-area -- yarn nps build-libs && tree packages/victory-area/{es,lib}
# ...
lerna success exec Executed command in 1 package: "yarn nps build-libs"
packages/victory-area/es
├── area.js
├── helper-methods.js
├── index.d.ts
├── index.js
└── victory-area.js
packages/victory-area/lib
├── area.js
├── helper-methods.js
├── index.d.ts
├── index.js
└── victory-area.js

0 directories, 10 files
```

and

```sh
$ lerna exec --scope victory-core -- yarn nps build-libs && tree packages/victory-core/{es,lib}
# ...
lerna success exec Executed command in 1 package: "yarn nps build-libs"
packages/victory-core/es
├── index.d.ts
├── index.js
├── types
│   ├── callbacks.d.ts
│   ├── callbacks.js
│   ├── prop-types.d.ts
│   └── prop-types.js
├── victory-accessible-group
│   ├── victory-accessible-group.d.ts
│   └── victory-accessible-group.js
├── victory-animation
│   ├── util.d.ts
│   ├── util.js
│   ├── victory-animation.d.ts
│   └── victory-animation.js
├── victory-clip-container
│   ├── victory-clip-container.d.ts
│   └── victory-clip-container.js
├── victory-container
│   ├── victory-container.d.ts
│   └── victory-container.js
├── victory-label
│   ├── victory-label.d.ts
│   └── victory-label.js
├── victory-portal
│   ├── portal-context.d.ts
│   ├── portal-context.js
│   ├── portal.d.ts
│   ├── portal.js
│   ├── victory-portal.d.ts
│   └── victory-portal.js
├── victory-primitives
│   ├── arc.d.ts
│   ├── arc.js
│   ├── background.d.ts
│   ├── background.js
│   ├── border.d.ts
│   ├── border.js
│   ├── circle.d.ts
│   ├── circle.js
│   ├── clip-path.d.ts
│   ├── clip-path.js
│   ├── index.d.ts
│   ├── index.js
│   ├── line-segment.d.ts
│   ├── line-segment.js
│   ├── line.d.ts
│   ├── line.js
│   ├── path.d.ts
│   ├── path.js
│   ├── point.d.ts
│   ├── point.js
│   ├── rect.d.ts
│   ├── rect.js
│   ├── text.d.ts
│   ├── text.js
│   ├── tspan.d.ts
│   ├── tspan.js
│   ├── types.d.ts
│   ├── types.js
│   ├── whisker.d.ts
│   └── whisker.js
├── victory-theme
│   ├── grayscale.d.ts
│   ├── grayscale.js
│   ├── material.d.ts
│   ├── material.js
│   ├── types.d.ts
│   ├── types.js
│   ├── victory-theme.d.ts
│   └── victory-theme.js
├── victory-transition
│   ├── victory-transition.d.ts
│   └── victory-transition.js
└── victory-util
    ├── add-events.js
    ├── axis.d.ts
    ├── axis.js
    ├── collection.d.ts
    ├── collection.js
    ├── common-props.d.ts
    ├── common-props.js
    ├── data.d.ts
    ├── data.js
    ├── default-transitions.d.ts
    ├── default-transitions.js
    ├── domain.d.ts
    ├── domain.js
    ├── events.js
    ├── helpers.d.ts
    ├── helpers.js
    ├── hooks
    │   ├── index.js
    │   ├── use-animation-state.js
    │   └── use-previous-props.js
    ├── immutable.d.ts
    ├── immutable.js
    ├── index.d.ts
    ├── index.js
    ├── label-helpers.d.ts
    ├── label-helpers.js
    ├── line-helpers.d.ts
    ├── line-helpers.js
    ├── log.d.ts
    ├── log.js
    ├── point-path-helpers.d.ts
    ├── point-path-helpers.js
    ├── prop-types.js
    ├── scale.d.ts
    ├── scale.js
    ├── selection.d.ts
    ├── selection.js
    ├── style.d.ts
    ├── style.js
    ├── textsize.d.ts
    ├── textsize.js
    ├── timer-context.d.ts
    ├── timer-context.js
    ├── timer.d.ts
    ├── timer.js
    ├── transitions.d.ts
    ├── transitions.js
    ├── user-props.d.ts
    ├── user-props.js
    ├── wrapper.d.ts
    └── wrapper.js
packages/victory-core/lib
├── index.d.ts
├── index.js
├── types
│   ├── callbacks.d.ts
│   ├── callbacks.js
│   ├── prop-types.d.ts
│   └── prop-types.js
├── victory-accessible-group
│   ├── victory-accessible-group.d.ts
│   └── victory-accessible-group.js
├── victory-animation
│   ├── util.d.ts
│   ├── util.js
│   ├── victory-animation.d.ts
│   └── victory-animation.js
├── victory-clip-container
│   ├── victory-clip-container.d.ts
│   └── victory-clip-container.js
├── victory-container
│   ├── victory-container.d.ts
│   └── victory-container.js
├── victory-label
│   ├── victory-label.d.ts
│   └── victory-label.js
├── victory-portal
│   ├── portal-context.d.ts
│   ├── portal-context.js
│   ├── portal.d.ts
│   ├── portal.js
│   ├── victory-portal.d.ts
│   └── victory-portal.js
├── victory-primitives
│   ├── arc.d.ts
│   ├── arc.js
│   ├── background.d.ts
│   ├── background.js
│   ├── border.d.ts
│   ├── border.js
│   ├── circle.d.ts
│   ├── circle.js
│   ├── clip-path.d.ts
│   ├── clip-path.js
│   ├── index.d.ts
│   ├── index.js
│   ├── line-segment.d.ts
│   ├── line-segment.js
│   ├── line.d.ts
│   ├── line.js
│   ├── path.d.ts
│   ├── path.js
│   ├── point.d.ts
│   ├── point.js
│   ├── rect.d.ts
│   ├── rect.js
│   ├── text.d.ts
│   ├── text.js
│   ├── tspan.d.ts
│   ├── tspan.js
│   ├── types.d.ts
│   ├── types.js
│   ├── whisker.d.ts
│   └── whisker.js
├── victory-theme
│   ├── grayscale.d.ts
│   ├── grayscale.js
│   ├── material.d.ts
│   ├── material.js
│   ├── types.d.ts
│   ├── types.js
│   ├── victory-theme.d.ts
│   └── victory-theme.js
├── victory-transition
│   ├── victory-transition.d.ts
│   └── victory-transition.js
└── victory-util
    ├── add-events.js
    ├── axis.d.ts
    ├── axis.js
    ├── collection.d.ts
    ├── collection.js
    ├── common-props.d.ts
    ├── common-props.js
    ├── data.d.ts
    ├── data.js
    ├── default-transitions.d.ts
    ├── default-transitions.js
    ├── domain.d.ts
    ├── domain.js
    ├── events.js
    ├── helpers.d.ts
    ├── helpers.js
    ├── hooks
    │   ├── index.js
    │   ├── use-animation-state.js
    │   └── use-previous-props.js
    ├── immutable.d.ts
    ├── immutable.js
    ├── index.d.ts
    ├── index.js
    ├── label-helpers.d.ts
    ├── label-helpers.js
    ├── line-helpers.d.ts
    ├── line-helpers.js
    ├── log.d.ts
    ├── log.js
    ├── point-path-helpers.d.ts
    ├── point-path-helpers.js
    ├── prop-types.js
    ├── scale.d.ts
    ├── scale.js
    ├── selection.d.ts
    ├── selection.js
    ├── style.d.ts
    ├── style.js
    ├── textsize.d.ts
    ├── textsize.js
    ├── timer-context.d.ts
    ├── timer-context.js
    ├── timer.d.ts
    ├── timer.js
    ├── transitions.d.ts
    ├── transitions.js
    ├── user-props.d.ts
    ├── user-props.js
    ├── wrapper.d.ts
    └── wrapper.js

24 directories, 228 files
```

**Comment by becca-bailey** [comment]
So, I'm still seeing test files show up in `lib` and `es` when we run `yarn nps watch`. This isn't a big deal since this particular command is only being run during local development, so I can close this issue for now. But it might be something to try to fix if we don't want to ignore built test files when we run tests during development.

**Comment by ryan-roemer** [comment]
Opened https://github.com/FormidableLabs/victory/pull/2321 to fix!

**Comment by becca-bailey** [comment]
Thanks @ryan-roemer!
