### ISSUE TITLE
use-context-selector could not be found on v.36.5.1

### ISSUE THREAD

**Issue by outaTiME** [FormidableLabs/victory#2326]
**Describe the bug**
I'm getting the following error after updating to the latest version of victory (36.5.1):

```
Unable to resolve module use-context-selector from /Users/outaTiME/Code/ambito-dolar/node_modules/victory-core/lib/victory-state/victory-provider.js: use-context-selector could not be found within the project or in these directories:
  ../../node_modules
  node_modules
  ../../node_modules
  13 | var React = _interopRequireWildcard(require("react"));
  14 |
> 15 | var _useContextSelector = require("use-context-selector");
     |                                    ^
  16 |
  17 | var _getData = require("./helpers/get-data");
  18 |
```

**Victory version**
victory@^36.5.1 / victory-native@^36.5.1

**Comment by Tyresius92** [comment]
I'm also seeing this even though the library I'm maintaining is on an earlier version (`36.4.0`) because `victory` specifies its dependencies as `"victory-area": "^36.4.0", so it's installing `36.5.1`. 

Because I think that sentence is unclear: 

My app installed the latest version of my lib. My lib has a dep on 36.4.0, but now my app breaks because it's installing your latest versions. 

(I know that this will be fixed by going to your _new_ latest, but this could probably have been avoided by using pinned versions here: https://github.com/FormidableLabs/victory/blob/main/packages/victory/package.json)

**Comment by Tyresius92** [comment]
I've updated my lib to `36.5.2`, but I'm now getting a broken TS build: 

```
node_modules/victory-vendor/d3-scale.d.ts:5:15 - error TS6137: Cannot import type declaration files. Consider importing 'd3-scale' instead of '@types/d3-scale'.

5 export * from "@types/d3-scale";
                ~~~~~~~~~~~~~~~~~

node_modules/victory-vendor/d3-shape.d.ts:5:15 - error TS6137: Cannot import type declaration files. Consider importing 'd3-shape' instead of '@types/d3-shape'.

5 export * from "@types/d3-shape";
                ~~~~~~~~~~~~~~~~~

node_modules/victory/lib/index.d.ts:16:33 - error TS2305: Module '"victory-brush-container"' has no exported member 'BrushHelpers'.

16 export { VictoryBrushContainer, BrushHelpers, brushContainerMixin, } from "victory-brush-container";
                                   ~~~~~~~~~~~~

node_modules/victory/lib/index.d.ts:16:47 - error TS2305: Module '"victory-brush-container"' has no exported member 'brushContainerMixin'.

16 export { VictoryBrushContainer, BrushHelpers, brushContainerMixin, } from "victory-brush-container";
                                                 ~~~~~~~~~~~~~~~~~~~

node_modules/victory/lib/index.d.ts:17:34 - error TS2305: Module '"victory-cursor-container"' has no exported member 'CursorHelpers'.

17 export { VictoryCursorContainer, CursorHelpers, cursorContainerMixin, } from "victory-cursor-container";
                                    ~~~~~~~~~~~~~

node_modules/victory/lib/index.d.ts:17:49 - error TS2305: Module '"victory-cursor-container"' has no exported member 'cursorContainerMixin'.

17 export { VictoryCursorContainer, CursorHelpers, cursorContainerMixin, } from "victory-cursor-container";
                                                   ~~~~~~~~~~~~~~~~~~~~

node_modules/victory/lib/index.d.ts:18:37 - error TS2305: Module '"victory-selection-container"' has no exported member 'SelectionHelpers'.

18 export { VictorySelectionContainer, SelectionHelpers, selectionContainerMixin, } from "victory-selection-container";
                                       ~~~~~~~~~~~~~~~~

node_modules/victory/lib/index.d.ts:18:55 - error TS2305: Module '"victory-selection-container"' has no exported member 'selectionContainerMixin'.

18 export { VictorySelectionContainer, SelectionHelpers, selectionContainerMixin, } from "victory-selection-container";
                                                         ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/victory/lib/index.d.ts:19:35 - error TS2305: Module '"victory-voronoi-container"' has no exported member 'VoronoiHelpers'.

19 export { VictoryVoronoiContainer, VoronoiHelpers, voronoiContainerMixin, } from "victory-voronoi-container";
                                     ~~~~~~~~~~~~~~

node_modules/victory/lib/index.d.ts:19:51 - error TS2305: Module '"victory-voronoi-container"' has no exported member 'voronoiContainerMixin'.

19 export { VictoryVoronoiContainer, VoronoiHelpers, voronoiContainerMixin, } from "victory-voronoi-container";
                                                     ~~~~~~~~~~~~~~~~~~~~~

node_modules/victory/lib/index.d.ts:20:32 - error TS2305: Module '"victory-zoom-container"' has no exported member 'ZoomHelpers'.

20 export { VictoryZoomContainer, ZoomHelpers, zoomContainerMixin, RawZoomHelpers, } from "victory-zoom-container";
                                  ~~~~~~~~~~~

node_modules/victory/lib/index.d.ts:20:45 - error TS2305: Module '"victory-zoom-container"' has no exported member 'zoomContainerMixin'.

20 export { VictoryZoomContainer, ZoomHelpers, zoomContainerMixin, RawZoomHelpers, } from "victory-zoom-container";
                                               ~~~~~~~~~~~~~~~~~~

node_modules/victory/lib/index.d.ts:20:65 - error TS2305: Module '"victory-zoom-container"' has no exported member 'RawZoomHelpers'.

20 export { VictoryZoomContainer, ZoomHelpers, zoomContainerMixin, RawZoomHelpers, } from "victory-zoom-container";
                                                                   ~~~~~~~~~~~~~~

node_modules/victory/lib/index.d.ts:21:10 - error TS2305: Module '"victory-create-container"' has no exported member 'combineContainerMixins'.

21 export { combineContainerMixins, makeCreateContainerFunction, createContainer, } from "victory-create-container";
            ~~~~~~~~~~~~~~~~~~~~~~

node_modules/victory/lib/index.d.ts:21:34 - error TS2305: Module '"victory-create-container"' has no exported member 'makeCreateContainerFunction'.

21 export { combineContainerMixins, makeCreateContainerFunction, createContainer, } from "victory-create-container";
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/victory/lib/index.d.ts:27:60 - error TS2305: Module '"victory-canvas"' has no exported member 'useCanvasContext'.

27 export { CanvasGroup, CanvasCurve, CanvasPoint, CanvasBar, useCanvasContext, } from "victory-canvas";
                                                              ~~~~~~~~~~~~~~~~

node_modules/victory/node_modules/victory-core/lib/victory-util/hooks/index.d.ts:2:35 - error TS7016: Could not find a declaration file for module './use-animation-state'. '/Users/tyrelclayton/codebase/fast-forward/node_modules/victory/node_modules/victory-core/lib/victory-util/hooks/use-animation-state.js' implicitly has an 'any' type.

2 export { useAnimationState } from "./use-animation-state";
                                    ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/victory/node_modules/victory-core/lib/victory-util/immutable.d.ts:1:42 - error TS2307: Cannot find module 'immutable' or its corresponding type declarations.

1 import type { Iterable, List, Map } from "immutable";
                                           ~~~~~~~~~~~

node_modules/victory/node_modules/victory-voronoi/lib/index.d.ts:15:18 - error TS2430: Interface 'VictoryVoronoiProps' incorrectly extends interface 'VictoryDatableProps'.
  Types of property 'sortKey' are incompatible.
    Type 'string[] | StringOrNumberOrCallback | undefined' is not assignable to type 'DataGetterPropType | undefined'.
      Type 'VictoryStringOrNumberCallback' is not assignable to type 'DataGetterPropType | undefined'.
        Type 'VictoryStringOrNumberCallback' is not assignable to type '(props: object) => string | number | string[] | number[]'.
          Types of parameters 'args' and 'props' are incompatible.
            Property 'index' is missing in type '{}' but required in type 'CallbackArgs'.

15 export interface VictoryVoronoiProps
                    ~~~~~~~~~~~~~~~~~~~

  node_modules/victory/node_modules/victory-core/lib/types/callbacks.d.ts:15:5
    15     index: ID;
           ~~~~~
    'index' is declared here.


Found 19 errors in 6 files.

Errors  Files
     1  node_modules/victory-vendor/d3-scale.d.ts:5
     1  node_modules/victory-vendor/d3-shape.d.ts:5
    14  node_modules/victory/lib/index.d.ts:16
     1  node_modules/victory/node_modules/victory-core/lib/victory-util/hooks/index.d.ts:2
     1  node_modules/victory/node_modules/victory-core/lib/victory-util/immutable.d.ts:1
     1  node_modules/victory/node_modules/victory-voronoi/lib/index.d.ts:15
ERROR: "build:dts" exited with 2.
```

**Comment by outaTiME** [comment]
The new version 36.5.2 working for me 🙌

**Comment by salunkeganesh** [comment]
I am getting following error after updating to latest version i.e (36.5.2)
`TypeError: Cannot read properties of undefined (reading 'animate')`
Before this I was using `^36.4.0` for which build had failed yesterday with 
`Unable to resolve module use-context-selector`

**Comment by becca-bailey** [comment]
This was resolved in 36.5.2. Sorry about the confusion!

**Comment by Tyresius92** [comment]
@becca-bailey what about the secondary issue that is still present in 36.5.2, described here: https://github.com/FormidableLabs/victory/issues/2326#issuecomment-1164947319 ?

Should I make a follow up issue for that?
