### ISSUE TITLE
Getting lots of TypeScript errors from within node_modules after upgrading to 36.5.3

### ISSUE THREAD

**Issue by kaiyoma** [FormidableLabs/victory#2358]
**Describe the bug**
After upgrading from 36.4.0 to 36.5.3, I get a lot of TypeScript errors from the Victory packages inside node_modules.

**Victory version**
36.5.3

**To Reproduce**
1. Upgrade to 36.5.3
2. Run the type checker

**Expected behavior**
No errors.

**Desktop (please complete the following information):**
 - OS: Linux, Windows 10
 - Browser: N/A

**Additional context**
Here are the type errors:

```
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(37,16): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(38,16): error TS7006: Parameter 'point' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(38,23): error TS7006: Parameter 'bounds' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(38,31): error TS7006: Parameter 'padding' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(39,16): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(39,23): error TS7006: Parameter 'fullDomain' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(39,35): error TS7006: Parameter 'selectedDomain' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(40,14): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(40,21): error TS7006: Parameter 'domainBox' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(41,20): error TS7006: Parameter 'point' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(41,27): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(41,34): error TS7006: Parameter 'domainBox' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(42,21): error TS7006: Parameter 'box' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(42,26): error TS7006: Parameter 'handles' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(44,23): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(44,36): error TS7006: Parameter 'cachedDomain' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(44,50): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(45,24): error TS7006: Parameter 'point' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(45,31): error TS7006: Parameter 'box' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(45,36): error TS7006: Parameter 'brushDimension' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(46,10): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(46,17): error TS7006: Parameter 'point' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(47,16): error TS7006: Parameter 'box' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(47,21): error TS7006: Parameter 'fullDomainBox' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(48,18): error TS7006: Parameter 'point' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(48,25): error TS7006: Parameter 'fullDomainBox' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(49,12): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(50,15): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(50,20): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(51,21): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(51,26): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(52,19): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(52,24): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-brush-container@36.5.3_react@17.0.2/node_modules/victory-brush-container/lib/index.d.ts(55,55): error TS2749: 'Component' refers to a value, but is being used as a type here. Did you mean 'typeof Component'?
../../common/temp/node_modules/.pnpm/victory-canvas@36.5.3_react@17.0.2/node_modules/victory-canvas/lib/index.d.ts(69,9): error TS7006: Parameter 'ctx' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-canvas@36.5.3_react@17.0.2/node_modules/victory-canvas/lib/index.d.ts(70,8): error TS7006: Parameter 'ctx' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-core@36.5.3_react@17.0.2/node_modules/victory-core/lib/victory-util/hooks/index.d.ts(2,35): error TS7016: Could not find a declaration file for module './use-animation-state'. 'C:/Work/event-viewer/common/temp/node_modules/.pnpm/victory-core@36.5.3_react@17.0.2/node_modules/victory-core/lib/victory-util/hooks/use-animation-state.js' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-core@36.5.3_react@17.0.2/node_modules/victory-core/lib/victory-util/immutable.d.ts(1,42): error TS2307: Cannot find module 'immutable' or its corresponding type declarations.
../../common/temp/node_modules/.pnpm/victory-create-container@36.5.3_react@17.0.2/node_modules/victory-create-container/lib/index.d.ts(14,40): error TS7006: Parameter 'mixins' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-create-container@36.5.3_react@17.0.2/node_modules/victory-create-container/lib/index.d.ts(14,48): error TS7006: Parameter 'Container' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-create-container@36.5.3_react@17.0.2/node_modules/victory-create-container/lib/index.d.ts(17,3): error TS7006: Parameter 'mixinMap' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-create-container@36.5.3_react@17.0.2/node_modules/victory-create-container/lib/index.d.ts(18,3): error TS7006: Parameter 'Container' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-create-container@36.5.3_react@17.0.2/node_modules/victory-create-container/lib/index.d.ts(19,7): error TS7006: Parameter 'behaviorA' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-create-container@36.5.3_react@17.0.2/node_modules/victory-create-container/lib/index.d.ts(19,18): error TS7006: Parameter 'behaviorB' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-cursor-container@36.5.3_react@17.0.2/node_modules/victory-cursor-container/lib/index.d.ts(30,16): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-cursor-container@36.5.3_react@17.0.2/node_modules/victory-cursor-container/lib/index.d.ts(31,16): error TS7006: Parameter 'point' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-cursor-container@36.5.3_react@17.0.2/node_modules/victory-cursor-container/lib/index.d.ts(31,23): error TS7006: Parameter 'bounds' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-cursor-container@36.5.3_react@17.0.2/node_modules/victory-cursor-container/lib/index.d.ts(32,15): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-cursor-container@36.5.3_react@17.0.2/node_modules/victory-cursor-container/lib/index.d.ts(32,20): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-cursor-container@36.5.3_react@17.0.2/node_modules/victory-cursor-container/lib/index.d.ts(33,16): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-cursor-container@36.5.3_react@17.0.2/node_modules/victory-cursor-container/lib/index.d.ts(33,21): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-cursor-container@36.5.3_react@17.0.2/node_modules/victory-cursor-container/lib/index.d.ts(34,14): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-cursor-container@36.5.3_react@17.0.2/node_modules/victory-cursor-container/lib/index.d.ts(34,19): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.5.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(32,16): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.5.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(33,15): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.5.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(34,18): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.5.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(34,25): error TS7006: Parameter 'datasets' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.5.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(34,35): error TS7006: Parameter 'bounds' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.5.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(35,19): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.5.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(35,26): error TS7006: Parameter 'dataset' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.5.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(36,15): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.5.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(36,20): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.5.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(37,15): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.5.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(37,20): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.5.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(38,13): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.5.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(38,18): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-vendor@36.5.1/node_modules/victory-vendor/d3-scale.d.ts(5,15): error TS6137: Cannot import type declaration files. Consider importing 'd3-scale' instead of '@types/d3-scale'.
../../common/temp/node_modules/.pnpm/victory-vendor@36.5.1/node_modules/victory-vendor/d3-shape.d.ts(5,15): error TS6137: Cannot import type declaration files. Consider importing 'd3-shape' instead of '@types/d3-shape'.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(25,16): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(25,23): error TS7006: Parameter 'point' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(26,15): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(27,14): error TS7006: Parameter 'datasets' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(27,24): error TS7006: Parameter 'point' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(28,16): error TS7006: Parameter 'point' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(28,23): error TS7006: Parameter 'mousePosition' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(28,38): error TS7006: Parameter 'radius' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(29,20): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(29,27): error TS7006: Parameter 'mousePosition' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(30,22): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(30,29): error TS7006: Parameter 'point' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(31,24): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(31,31): error TS7006: Parameter 'point' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(32,21): error TS7006: Parameter 'activePoints' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(32,35): error TS7006: Parameter 'mousePosition' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(32,50): error TS7006: Parameter 'parentSVG' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(32,61): error TS7006: Parameter 'vIndex' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(33,15): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(33,22): error TS7006: Parameter 'points' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(34,17): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(34,24): error TS7006: Parameter 'points' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(35,16): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(35,21): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(36,15): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.5.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(36,20): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi@36.5.3_react@17.0.2/node_modules/victory-voronoi/lib/index.d.ts(15,18): error TS2430: Interface 'VictoryVoronoiProps' incorrectly extends interface 'VictoryDatableProps'.
  Types of property 'sortKey' are incompatible.
    Type 'string[] | StringOrNumberOrCallback | undefined' is not assignable to type 'DataGetterPropType | undefined'.
      Type 'VictoryStringOrNumberCallback' is not assignable to type 'DataGetterPropType | undefined'.
        Type 'VictoryStringOrNumberCallback' is not assignable to type '(props: object) => string | number | string[] | number[]'.
          Types of parameters 'args' and 'props' are incompatible.
            Property 'index' is missing in type '{}' but required in type 'CallbackArgs'.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(27,23): error TS7006: Parameter 'a' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(27,26): error TS7006: Parameter 'b' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(28,9): error TS7006: Parameter 'currentDomain' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(28,24): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(28,29): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(28,36): error TS7006: Parameter 'axis' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(29,19): error TS7006: Parameter 'currentDomain' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(29,34): error TS7006: Parameter 'factor' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(29,42): error TS7006: Parameter 'percent' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(30,20): error TS7006: Parameter 'point' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(30,27): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(30,34): error TS7006: Parameter 'axis' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(31,15): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(32,18): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(33,19): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(33,24): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(33,31): error TS7006: Parameter 'axis' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(34,15): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(34,20): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(34,27): error TS7006: Parameter 'originalDomain' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(35,7): error TS7006: Parameter 'currentDomain' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(35,22): error TS7006: Parameter 'originalDomain' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(35,38): error TS7006: Parameter 'delta' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(36,18): error TS7006: Parameter 'domain' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(36,26): error TS7006: Parameter 'scale' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(36,33): error TS7006: Parameter 'axis' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(37,19): error TS7006: Parameter 'ctx' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(38,17): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(38,30): error TS7006: Parameter 'originalDomain' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(39,13): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(40,15): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(40,20): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(41,13): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(41,18): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(42,16): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(42,21): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(43,15): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(43,20): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(43,33): error TS7006: Parameter 'eventKey' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(43,43): error TS7006: Parameter 'ctx' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(44,11): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(44,16): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(44,29): error TS7006: Parameter 'eventKey' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(44,39): error TS7006: Parameter 'ctx' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.5.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(48,3): error TS2749: 'RawZoomHelpers' refers to a value, but is being used as a type here. Did you mean 'typeof RawZoomHelpers'?
```

**Comment by kaiyoma** [comment]
I tried opening one of the node_modules files and sure enough, vscode points out all the same errors:

![image](https://user-images.githubusercontent.com/10719780/178563086-697cf97e-3e44-4744-bd79-4db4b4b14c30.png)

There seem to be a lot of TS issues in Victory itself. Shouldn't the build process be catching these things?

**Comment by jasherman** [comment]
I can repro this same issue after upgrading from 36.3.2 to 36.5.3

**Comment by jasherman** [comment]
> I can repro this same issue after upgrading from 36.3.2 to 36.5.3
> 
> I also tried going back to 36.4.0 and I get the same errors.

@becca-bailey is this something you might be able to help get prioritized.  I can not upgrade beyond 36.3.2.  Probably related to running typescript in strict mode where inferred 'any' types are not allowed.

**Comment by scottrippey** [comment]
Does this issue still persist in the latest build? `36.6.2` was just release to address a number of TS issues.

**Comment by kaiyoma** [comment]
@scottrippey I'm still seeing a ton of type errors after upgrading to 36.6.3:

```
[7:49:02 PM] x ../../common/temp/node_modules/.pnpm/victory-canvas@36.6.3_react@17.0.2/node_modules/victory-canvas/lib/index.d.ts(69,9): error TS7006: Parameter 'ctx' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-canvas@36.6.3_react@17.0.2/node_modules/victory-canvas/lib/index.d.ts(70,8): error TS7006: Parameter 'ctx' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-core@36.6.3_react@17.0.2/node_modules/victory-core/lib/victory-util/immutable.d.ts(1,42): error TS2307: Cannot find module 'immutable' or its corresponding type declarations.
../../common/temp/node_modules/.pnpm/victory-create-container@36.6.3_react@17.0.2/node_modules/victory-create-container/lib/index.d.ts(14,40): error TS7006: Parameter 'mixins' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-create-container@36.6.3_react@17.0.2/node_modules/victory-create-container/lib/index.d.ts(14,48): error TS7006: Parameter 'Container' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-create-container@36.6.3_react@17.0.2/node_modules/victory-create-container/lib/index.d.ts(17,3): error TS7006: Parameter 'mixinMap' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-create-container@36.6.3_react@17.0.2/node_modules/victory-create-container/lib/index.d.ts(18,3): error TS7006: Parameter 'Container' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-create-container@36.6.3_react@17.0.2/node_modules/victory-create-container/lib/index.d.ts(19,7): error TS7006: Parameter 'behaviorA' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-create-container@36.6.3_react@17.0.2/node_modules/victory-create-container/lib/index.d.ts(19,18): error TS7006: Parameter 'behaviorB' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.6.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(32,16): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.6.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(33,15): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.6.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(34,18): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.6.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(34,25): error TS7006: Parameter 'datasets' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.6.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(34,35): error TS7006: Parameter 'bounds' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.6.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(35,19): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.6.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(35,26): error TS7006: Parameter 'dataset' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.6.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(36,15): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.6.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(36,20): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.6.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(37,15): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.6.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(37,20): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.6.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(38,13): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-selection-container@36.6.3_react@17.0.2/node_modules/victory-selection-container/lib/index.d.ts(38,18): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-vendor@36.6.3/node_modules/victory-vendor/d3-scale.d.ts(5,15): error TS6137: Cannot import type declaration files. Consider importing 'd3-scale' instead of '@types/d3-scale'.
../../common/temp/node_modules/.pnpm/victory-vendor@36.6.3/node_modules/victory-vendor/d3-shape.d.ts(5,15): error TS6137: Cannot import type declaration files. Consider importing 'd3-shape' instead of '@types/d3-shape'.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(25,16): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(25,23): error TS7006: Parameter 'point' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(26,15): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(27,14): error TS7006: Parameter 'datasets' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(27,24): error TS7006: Parameter 'point' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(28,16): error TS7006: Parameter 'point' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(28,23): error TS7006: Parameter 'mousePosition' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(28,38): error TS7006: Parameter 'radius' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(29,20): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(29,27): error TS7006: Parameter 'mousePosition' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(30,22): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(30,29): error TS7006: Parameter 'point' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(31,24): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(31,31): error TS7006: Parameter 'point' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(32,21): error TS7006: Parameter 'activePoints' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(32,35): error TS7006: Parameter 'mousePosition' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(32,50): error TS7006: Parameter 'parentSVG' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(32,61): error TS7006: Parameter 'vIndex' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(33,15): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(33,22): error TS7006: Parameter 'points' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(34,17): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(34,24): error TS7006: Parameter 'points' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(35,16): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(35,21): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(36,15): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-voronoi-container@36.6.3_react@17.0.2/node_modules/victory-voronoi-container/lib/index.d.ts(36,20): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(27,23): error TS7006: Parameter 'a' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(27,26): error TS7006: Parameter 'b' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(28,9): error TS7006: Parameter 'currentDomain' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(28,24): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(28,29): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(28,36): error TS7006: Parameter 'axis' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(29,19): error TS7006: Parameter 'currentDomain' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(29,34): error TS7006: Parameter 'factor' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(29,42): error TS7006: Parameter 'percent' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(30,20): error TS7006: Parameter 'point' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(30,27): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(30,34): error TS7006: Parameter 'axis' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(31,15): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(32,18): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(33,19): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(33,24): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(33,31): error TS7006: Parameter 'axis' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(34,15): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(34,20): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(34,27): error TS7006: Parameter 'originalDomain' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(35,7): error TS7006: Parameter 'currentDomain' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(35,22): error TS7006: Parameter 'originalDomain' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(35,38): error TS7006: Parameter 'delta' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(36,18): error TS7006: Parameter 'domain' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(36,26): error TS7006: Parameter 'scale' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(36,33): error TS7006: Parameter 'axis' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(37,19): error TS7006: Parameter 'ctx' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(38,17): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(38,30): error TS7006: Parameter 'originalDomain' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(39,13): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(40,15): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(40,20): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(41,13): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(41,18): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(42,16): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(42,21): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(43,15): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(43,20): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(43,33): error TS7006: Parameter 'eventKey' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(43,43): error TS7006: Parameter 'ctx' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(44,11): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(44,16): error TS7006: Parameter 'targetProps' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(44,29): error TS7006: Parameter 'eventKey' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(44,39): error TS7006: Parameter 'ctx' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.3_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(48,3): error TS2749: 'RawZoomHelpers' refers to a value, but is being used as a type here. Did you mean 'typeof RawZoomHelpers'?
```

**Comment by scottrippey** [comment]
I think I see the problem now. The packages that are causing these build issues are all ones that haven't been converted to TypeScript yet. These have manually-written `index.d.ts` files, which allow implicit `any` with our tsconfig. We added several missing types to these files, starting in `36.4.0`.
All the rest of our (converted to TypeScript) packages now have generated `*.d.ts` which adds the explicit `any` automatically. 

Anyway, all this to say, I think I have a solution and I'll try to get it fixed asap!

**Comment by scottrippey** [comment]
Just published `36.6.4`, which explicitly adds the `any` type for the typings that were missing it.
I do think this will resolve 95% of the errors posted.  Please verify when possible!

There seem to be a few more other issues in those logs, not related to implicit any's, which are probably not solved.  I will continue researching those.

**Comment by kaiyoma** [comment]
@scottrippey Much better! But I'm still seeing some type errors:

```
[4:46:03 PM] x ../../common/temp/node_modules/.pnpm/victory-core@36.6.4_react@17.0.2/node_modules/victory-core/lib/victory-util/immutable.d.ts(1,42): error TS2307: Cannot find module 'immutable' or its corresponding type declarations.
../../common/temp/node_modules/.pnpm/victory-vendor@36.6.4/node_modules/victory-vendor/d3-scale.d.ts(5,15): error TS6137: Cannot import type declaration files. Consider importing 'd3-scale' instead of '@types/d3-scale'.
../../common/temp/node_modules/.pnpm/victory-vendor@36.6.4/node_modules/victory-vendor/d3-shape.d.ts(5,15): error TS6137: Cannot import type declaration files. Consider importing 'd3-shape' instead of '@types/d3-shape'.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.4_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(31,15): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.4_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(32,18): error TS7006: Parameter 'evt' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.4_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(37,19): error TS7006: Parameter 'ctx' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.4_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(39,13): error TS7006: Parameter 'props' implicitly has an 'any' type.
../../common/temp/node_modules/.pnpm/victory-zoom-container@36.6.4_react@17.0.2/node_modules/victory-zoom-container/lib/index.d.ts(48,3): error TS2749: 'RawZoomHelpers' refers to a value, but is being used as a type here. Did you mean 'typeof RawZoomHelpers'?
```

**Comment by adamlutz** [comment]
Thanks for addressing these issues @scottrippey.  Unfortunately, we're also seeing these last few TS errors that @kaiyoma mentioned above.  

After upgrading to 36.6.4, we were forced to rollback all the way to v35 latest b/c we couldn't downgrade to something like 36.3.x before the typescript errors started.

**Comment by scottrippey** [comment]
I've created #2439 to handle these remaining issues separately!

**Comment by scottrippey** [comment]
I just published `36.6.5`, which fixes these last remaining issues.  Hopefully this unblocks you all!  Please report back if there are any remaining issues.

**Comment by kaiyoma** [comment]
@scottrippey All the type errors are gone after upgrading to the latest version. Thanks for all the fixes!

**Comment by adamlutz** [comment]
Thankis @scottrippey -- we are still seeing 4 issues in our build process:

```
node_modules/victory-brush-container/lib/brush-helpers.d.ts(5,41): error TS2694: Namespace '_' has no exported member 'DebouncedFunc'.
node_modules/victory-cursor-container/lib/cursor-helpers.d.ts(7,35): error TS2694: Namespace '_' has no exported member 'DebouncedFunc'.
node_modules/victory-native/src/components/victory-brush-container.d.ts(7,50): error TS2749: 'VictoryBrushContainer' refers to a value, but is being used as a type here. Did you mean 'typeof VictoryBrushContainer'?
node_modules/victory-native/src/components/victory-cursor-container.d.ts(7,51): error TS2749: 'VictoryCursorContainer' refers to a value, but is being used as a type here. Did you mean 'typeof VictoryCursorContainer'?
```
