### ISSUE TITLE
Mutation not changing label on the first mouse-over event

### ISSUE THREAD

**Issue by gabrielmdeal** [FormidableLabs/victory#759]
I have a `VictoryBar` component with a `onMouseOver` event mutation on a `labelComponent` that does not update the label -- but this problem only happens on the first mouse-over event.  It happens despite the first mouse-over triggering a call to the `mutate` callback.  Subsequent mouse-overs do update the label.  

This behavior seems to be triggered by setting state in React's first `componentDidMount` call.  The state change itself does not seem to be the problem because the bug will happen even if I change a state value that nothing uses.  I assume it is the immediate re-render that triggers the problem.

This reproduces my problem: https://jsfiddle.net/gabrielx/4ohdry0j/  The comment in the HTML section explains a bit more.

I am totally baffled.  Am I doing something wrong here or is this a bug in Victory?

I have reproduced this on Linux Chrome 61, Linux Firefox 55, and Windows 10 Edge 40.  Haven't tried anywhere else.

**Comment by karuzo17** [comment]
I'm experiencing a similar issue. On react native my VictoryPie slices only change their colours after the second onPressIn event. I think this is caused by a Victory Bug.

**Comment by boygirl** [comment]
@gabrielmdeal @karuzo17 I believe this is fixed in the latest version

**Comment by gabrielmdeal** [comment]
I just updated my jsfiddle to verify the fix in victory v24.5 but I still get the buggy behavior.  https://jsfiddle.net/4ohdry0j/20/
